

name: ECR Image Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # AWS Configure
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      # AWS login ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.ECR_IMAGE }}:${{ github.sha }} .

      # Image Tag
      - name: tag to Image
        run: docker tag ${{ secrets.ECR_IMAGE }}:${{ github.sha }} ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_IMAGE }}:${{ github.sha }}

      # Push Image to ECR
      - name: Push Image to ECR
        run: docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_IMAGE }}:${{ github.sha }}

      # kube 설치
      - name: Download kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.18.0/bin/linux/amd64/kubectl"
          chmod +x kubectl

      # kube 환경변수 설정
      - name: Add kubectl to PATH
        run: |
          sudo mv kubectl /usr/local/bin/

      # Update kubo 구름 클러스터 등록
      - name: Kubectl update
        run: aws eks update-kubeconfig --region ap-northeast-2 --name goormthon-cluster

      #  kube config
      - name: kube config
        run: |
          mkdir -p $HOME/.kube
          cd $HOME/.kube
          touch ./config
          echo "${{ secrets.KUBECONFIG }}" > ./config

      # Update kubo 구름 클러스터 등록_2
      - name: Kubectl update
        run: aws eks update-kubeconfig --region ap-northeast-2 --name goormthon-cluster

      # Update deploy image
      - name: Update deploy image
        run: kubectl set image deployment/hello-deploy-alb hello-app=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_IMAGE }}:${{ github.sha }} -n jeju-senior
